import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header/header";
import ReactQueryProvider from "../utils/provider/reactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stonks Fullstack app test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <Header />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
